language: java

addons:
  sonarcloud:
    organization: "nareshkumar-h-github"
    token:
      secure: $SONAR_TOKEN
    
jobs:
  include:
    - stage: pre-build
      script: mvn clean
  
    - stage: test
      script: mvn test org.jacoco:jacoco-maven-plugin:prepare-agent
    
    - stage: build
      script: mvn install
      
    - stage: quality
      script: mvn sonar:sonar

#script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  #- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
notifications:
  slack: javafullstackgroup:cU6yGmSyVRshhITnnXELpBug
  

  
  
